import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const home = readFileSync('index.html', 'utf8');
const feature = home.match(/<aside[^>]*aria-labelledby="featured-managed-it-title"[^>]*>([\s\S]*?)<\/aside>/)?.[1];
assert.ok(feature, 'homepage must feature Managed IT');
assert.match(home, /<title>Managed IT &amp; Business IT Support in Lexington, SC \| StrataWorks<\/title>/);
assert.match(home, /<meta name="description" content="Managed IT support for businesses with 1–15 employees in Lexington and Columbia, SC\. Talk with StrataWorks about support tailored to your business\.\">/);
assert.match(home, /<h1>Managed IT for<br><span>small businesses\.<\/span><\/h1>/);
assert.match(home, /Practical, ongoing IT support for teams of 1–15 employees in Lexington, Columbia, and the Midlands\./);
assert.match(home, /href="#contact">Discuss Your IT Needs/);
assert.match(home, /<a class="text-link" href="\/managed-it-services\/">Explore Managed IT/);
assert.match(home, /<nav[^>]*id="site-nav"[\s\S]*href="\/managed-it-services\/">Managed IT/);
assert.match(feature, /FEATURED SERVICE \/ MANAGED IT/);
assert.match(feature, /<h3 id="featured-managed-it-title">Your IT department, without the full-time overhead\.<\/h3>/);
assert.match(feature, /href="\/managed-it-services\/">Explore Managed IT/);
assert.match(feature, /href="\/managed-it-services\/#consultation">Talk With StrataWorks/);
assert.match(readFileSync('managed-it-services/index.html', 'utf8'), /id="consultation"/);
const services = home.match(/<section class="section services"[\s\S]*?<\/section>/)[0];
assert.ok(services.includes(feature), 'feature belongs in Capabilities');
assert.ok(services.indexOf('FEATURED SERVICE / MANAGED IT') < services.indexOf('02 / STRATAWORKS BACKFLOW OPERATIONS'), 'Managed IT feature must precede the backflow platform');
assert.match(services, /href="managed-it-services\/">Need ongoing IT support\?/);
assert.match(services, /Backflow Operations Platform/);
assert.match(services, /href="backflow-operations-platform\/#pricing">Lock in the \$300 rate/);
assert.match(services, /href="backflow-operations-platform\/">Explore Backflow Operations/);
assert.equal((services.match(/<article class="service-card /g) || []).length, 6);
const footer = home.match(/<footer\b[\s\S]*?<\/footer>/)[0];
assert.match(footer, /href="\/managed-it-services\/">Managed IT Services<\/a>/);
const google = footer.match(/<a\b[^>]*href="https:\/\/share\.google\/gXDWkEUj6sbTTJFo4"[^>]*>/)?.[0];
assert.ok(google, 'footer must link to the Google Business Profile');
assert.match(google, /target="_blank"/);
assert.match(google, /rel="noopener noreferrer"/);
console.log('Homepage discoverability regression checks passed.');
assert.match(google, /aria-label="Find StrataWorks on Google"/);
assert.match(footer, /<img src="assets\/google-logo.png" alt="Google"/);
for (const label of ['Computers + Microsoft 365', 'Networks + Wi-Fi', 'Backups + security', 'Phones + vendors']) assert.ok(feature.includes(label));
